routes/web.php
<?php

use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\PrescriptionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [IndexController::class, 'index']);

Route::middleware(['auth'])->group(function () {
    Route::get('/', [IndexController::class, 'dashboard'])->name('dashboard');

    Route::get('/inventory', [InventoryController::class, 'index'])->name('inventory');

    Route::prefix('prescriptions')->name('prescriptions.')->group(function () {
        Route::get('/', [PrescriptionController::class, 'index'])->name('index');
        Route::get('/create', [PrescriptionController::class, 'getCreateForm'])->name('createForm');
        Route::post('/create', [PrescriptionController::class, 'create'])->name('create');
    });

    Route::prefix('deliveries')->name('deliveries.')->group(function () {
        Route::get('/', [DeliveryController::class, 'index'])->name('index');
        Route::get('/create', [DeliveryController::class, 'getCreateForm'])->name('getCreateForm');
    });
});

require __DIR__ . '/auth.php';

app/Models/Delivery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Delivery extends Model
{
    use HasFactory;

    protected $with = [
        'content',
        'reciever'
    ];

    public function content()
    {
        return $this->hasMany(DeliveryContent::class);
    }

    public function reciever()
    {
        return $this->belongsTo(User::class, 'recipient_user_id');
    }
}

app/Http/Controllers/DeliveryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Delivery;
use App\Service\DeliveryService;
use Illuminate\Http\Request;

class DeliveryController extends Controller
{
    //

    protected $deliveryService;

    public function __construct(DeliveryService $deliveryService)
    {
        $this->deliveryService = $deliveryService;
    }

    public function index(Request $request)
    {
        $data = $this->deliveryService->getDeliveryData($request->user()->location);
        return view('sb-admin.deliveries.index', $data);
    }

    public function getCreateForm(Request $request)
    {
        $data = $this->deliveryService->getCreateFormData();
        return view('sb-admin.deliveries.create', $data);
    }
}

app/View/Components/AdminLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AdminLayout extends Component
{

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.sb-admin');
    }
}

resources/views/sb-admin/deliveries/create.blade.php
<x-admin-layout>
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <h1 class="mt-4">Create Delivery</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{{route('deliveries.index')}}">Deliveries</a></li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
        <form action="{{route('deliveries.create')}}" id="deliveryForm" method="post" onsubmit="return validateForm()">
            @csrf
            <div class="form-group">
                <label for="id_in_receipt">Id on Receipt:</label>
                <input type="text" class="form-control" id="id_in_receipt" placeholder="Enter Id on receipt" name="id_in_receipt" required>
            </div>
            <div class="form-group">
                <label for="id_in_notebook">Id in Notebook:</label>
                <input type="text" class="form-control" id="id_in_notebook" placeholder="Enter Id on notebook" name="id_in_notebook" required>
            </div>
            <div class="form-group">
                <label for="deliverer">Deliverer:</label>
                <input type="text" class="form-control" id="deliverer" placeholder="Enter deliverer" name="deliverer" required>
            </div>
            <div id="delivery-content">
                <div class="form-group form-inline">
                    <label for="">Medicine:
                        <div>
                            <select class="form-control" id="" name="deliveryContent[0][medicine_id]" onblur="isMedicineDuplicateFound()" required>
                            @foreach ($medicines as $medicine)
                                <option value="{{$medicine->id}}">{{$medicine->name}}</option>
                            @endforeach
                            </select>
                            <div class="invalid-feedback"></div>
                        </div>
                    </label>
                    <label for="">Amount:
                        <div>
                            <input type="number" class="form-control" id="" name="deliveryContent[0][amountInBoxes]" value="0" pattern="[0-9]+""  onblur="isAmountRequestedValid(this)" placeholder="Amount in boxes" required>
                            <div class="invalid-feedback"></div>
                        </div>
                    </label>
                    <i class="fas fa-plus-circle" onclick="appendForm()"></i>
                </div>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Submit</button>
            </div>


        </form>

    </div>

    <x-slot name="scripts">
        <script>
            var counter = 1;

            function validateForm(){
                formIsValid = true;

                if (isMedicineDuplicateFound()) formIsValid = false;

                $('#delivery-content input').each(function(key, selectInput) {
                    if(!isAmountRequestedValid(selectInput)) formIsValid = false;
                });
                return formIsValid;
            }

            function isMedicineDuplicateFound() {
                console.log('test');
                tempMedicineMap = [];
                foundError = false;
                $('#delivery-content select').each(function(key, selectInput){

                    if(typeof tempMedicineMap[selectInput.value] === 'undefined') {
                        tempMedicineMap[selectInput.value] = 1;
                        unSetInputInvalid(selectInput);
                    }
                    else {
                        tempMedicineMap[selectInput.value]++;
                        console.log(tempMedicineMap[selectInput.value]);
                        if (tempMedicineMap[selectInput.value] > 1) {
                            setInputInvalid(selectInput, 'Medicine is already in the list');
                            foundError = true;
                        } else {
                            unSetInputInvalid(selectInput);
                        }
                    }
                });
                return foundError;
            }

            function appendForm(){
                $('#delivery-content').append(
                `
                <div class="form-group form-inline">
                    <label for="">Medicine:
                        <div>
                            <select class="form-control" id="" name="deliveryContent[`+counter+`][medicine_id]" onblur="isMedicineDuplicateFound()" required>
                            @foreach ($medicines as $medicine)
                                <option value="{{$medicine->id}}">{{$medicine->name}}</option>
                            @endforeach
                            </select>
                            <div class="invalid-feedback"></div>
                        </div>
                    </label>
                    <label for="">Amount:
                        <div>
                            <input type="number" class="form-control" id="" name="deliveryContent[`+counter+`][amountInBoxes]" value="0" pattern="[0-9]+""  onblur="isAmountRequestedValid(this)" placeholder="Amount in boxes" required>
                            <div class="invalid-feedback"></div>
                        </div>
                    </label>
                    <i class="fas fa-plus-circle" onclick="appendForm()"></i>
                    <i class="fas fa-minus-circle" onclick="removeFromForm(this)"></i>
                </div>
                `
                );

                counter++;
            }

            function removeFromForm(deliveryContentGroup){
                $(deliveryContentGroup).parent().remove();
            }

            function isAmountRequestedValid(input) {
                inputValue = parseInt(input.value == '' ? 0 : input.value);
                if(inputValue === NaN || inputValue <= 0){
                    setInputInvalid(input, 'Invalid Number');
                    return false;
                }else{
                    unSetInputInvalid(input);
                    return true;
                }
            }

            function setInputInvalid(input, msg) {

                $(input).addClass('is-invalid');
                $(input).parent().find('.invalid-feedback').first().text(msg);
            }

            function unSetInputInvalid(input) {
                $(input).removeClass('is-invalid');
            }

        </script>
    </x-slot>
</x-admin-layout>

resources/views/sb-admin/deliveries/index.blade.php
<x-admin-layout>
    <!-- Begin Page Content -->
    <div class="container-fluid">
        <h1 class="mt-4">Tables</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
            <li class="breadcrumb-item active">Deliveries</li>
        </ol>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Deliveries in <?=$locationName?>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <x-datatables tableId="deliveriesTable">
                        <x-slot name="thead">
                            <tr>
                                <th></th>
                                <th>Id in receipt</th>
                                <th>Id in notebook</th>
                                <th>Delvierer</th>
                                <th>Reciever</th>
                                <th>Datetime</th>
                            </tr>
                        </x-slot>
                        <x-slot name="tfoot">
                            <tr>
                                <th></th>
                                <th>Id in receipt</th>
                                <th>Id in notebook</th>
                                <th>Delvierer</th>
                                <th>Reciever</th>
                                <th>Datetime</th>
                            </tr>
                        </x-slot>
                        <x-slot name="tbody">
                            @foreach ($deliveries as $deliveryItem)
                            <tr>
                                <td class="details-control" style="text-align:center">
                                    <i class="fas fa-plus-circle"></i>
                                    <div style="display: none;">{{$deliveryItem->id}}</div>
                                </td>
                                <td>{{$deliveryItem->id_in_receipt}}</td>
                                <td>{{$deliveryItem->id_in_notebook}}</td>
                                <td>{{$deliveryItem->deliverer}}</td>
                                <td>{{$deliveryItem->reciever->firstname.' '.$deliveryItem->reciever->lastname}}</td>
                                <td>{{$deliveryItem->created_at}}</td>
                            </tr>
                            @endforeach
                        </x-slot>
                    </x-datatables>
                </div>
            </div>
        </div>
    </div>

    <x-modal :canFade=true modalId="deliveryContentModal" :modalLarge=true>
        <x-slot name="modalTitle">
            Delivery Content
        </x-slot>
        <x-slot name="modalBody">
            <x-datatables tableId="deliveryContentTable">
                <x-slot name="thead">
                    <tr>
                        <th>Medicine</th>
                        <th>Type</th>
                        <th>Amount</th>
                    </tr>
                </x-slot>
                <x-slot name="tfoot">
                    <tr>
                        <th>Medicine</th>
                        <th>Type</th>
                        <th>Amount</th>
                    </tr>
                </x-slot>
                <x-slot name="tbody">

                </x-slot>
            </x-datatables>
        </x-slot>
    </x-modal>


    <x-modal modalId="loadingModal" :modalLarge=false>
        <x-slot name="modalTitle">
            Loading ...
        </x-slot>
        <x-slot name="modalBody">
            <div style="text-align: center; font-size: 10rem; color: #007bff">
                <i class="fas fa-spinner fa-spin"></i>
            </div>
        </x-slot>
    </x-modal>

    <x-modal modalId="errorModal" :modalLarge=false>
        <x-slot name="modalTitle">
            Something happened!!!
        </x-slot>
        <x-slot name="modalBody">
            <div style="text-align: center; font-size: 10rem; color: #ff0000">
                <i class="fas fa-times-circle"></i>
            </div>
        </x-slot>
    </x-modal>

    <x-slot name="scripts">
        <script>
            $(document).ready(function() {
                $('#deliveriesTable').DataTable();

                $('#deliveriesTable > tbody').on('click', 'td.details-control', function () {
                    var deliveryId = $(this).closest('td').find('div').text();
                    $.ajax("{{route('api.deliveries.content')}}",{
                        method: "GET",
                        data: {"delivery_id": deliveryId},
                        beforeSend: function() {
                            $('#loadingModal').modal();
                        }
                    }).always(function(){
                        $('#loadingModal').modal('hide');
                    }).fail(function(){
                        $('#errorModal').modal();
                    }).done(function(data) {
                        var deliveryContentTableHtml = "";
                        $.each(data,function(key,row){
                            deliveryContentTableHtml+=`
                            <tr>
                                <td>`+row.medicine.name+`</td>
                                <td>`+row.medicine.type.name+`</td>
                                <td>`+row.amount_in_boxes+`</td>
                            </tr>
                            `;
                        });

                        $('#deliveryContentTable tbody').html(deliveryContentTableHtml);

                        $('#deliveryContentModal').modal();
                    });
                });
            });


        </script>

    </x-slot>
</x-admin-layout>